VERSION 0.8 
FROM --pass-args ..+base

IMPORT .. AS tests

WORKDIR /test

test-all:
    DO tests+RUN_earthbuild --earthfile=manifest.earth --target=+gha
    RUN acbgrep '^::group::' earthbuild.output
    RUN acbgrep -v '^should have prefix' earthbuild.output
    RUN acbgrep '^::endgroup::' earthbuild.output
