VERSION 0.8

FROM alpine:3.24.0

test:
  RUN echo "hello world 2"
  ARG FILE_NAME_PREFIX="helloworld"
  LET file_name="${FILE_NAME_PREFIX}2"
  RUN echo "hello world 2" > $file_name
  SAVE ARTIFACT $file_name

testdir:
    WORKDIR /somedir2
    RUN echo "hello world in dir" > somefile2
    SAVE ARTIFACT /somedir2
