VERSION 0.8
FROM golang:1.26-alpine3.23
RUN apk --no-cache add git curl
WORKDIR /go-example

all:
  BUILD +lint
  BUILD +docker

build:
  COPY main.go .
  RUN go build -o build/go-example main.go
  SAVE ARTIFACT build/go-example AS LOCAL build/go-example

lint:
  FROM golangci/golangci-lint:v2.12.2-alpine:3.24.0
  COPY main.go .
  RUN golangci-lint run main.go

docker:
  COPY +build/go-example .
  ENTRYPOINT ["/go-example/go-example"]
  SAVE IMAGE go-example:latest
