VERSION 0.8
FROM amazoncorretto:25.0.3-alpine3.22
RUN apk add --no-cache gradle openjdk21
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
WORKDIR /java-example

build:
    COPY build.gradle ./
    COPY src src
    RUN gradle build
    RUN gradle install
    SAVE ARTIFACT build/install/java-example/bin /bin
    SAVE ARTIFACT build/install/java-example/lib /lib

docker:
    COPY +build/bin bin
    COPY +build/lib lib
    ENTRYPOINT ["/java-example/bin/java-example"]
    SAVE IMAGE java-example:latest
