package cli_test

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

var (
	earthCmdMu sync.Mutex
	testBinary string
)

func TestMain(m *testing.M) {
	binary, cleanup, err := buildEarthBinary()
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "failed to build earth test binary: %v\n", err)

		os.Exit(1)
	}

	testBinary = binary
	code := m.Run()

	cleanup()
	os.Exit(code)
}

func TestBuiltinArgCannotBePassedOnCommandLine(t *testing.T) {
	t.Parallel()

	for _, versionLine := range []string{
		"VERSION 0.8",
		"VERSION --arg-scope-and-set 0.8",
	} {
		t.Run(versionLine, func(t *testing.T) {
			t.Parallel()

			projectDir := copyFixtureDir(t, "builtin-args")
			replaceVersionLine(t, filepath.Join(projectDir, "Earthfile"), versionLine)

			out, err := runEarth(t, projectDir,
				"--no-output",
				"--build-arg", "EARTHLY_VERSION=123",
				"+builtin-args-test",
			)

			require.Error(t, err)
			require.Contains(t, out, "cannot be passed on the command line")
		})
	}
}

func buildEarthBinary() (string, func(), error) {
	if binary := os.Getenv("EARTHLY_TEST_BINARY"); binary != "" {
		return binary, func() {}, nil
	}

	dir, err := os.MkdirTemp("", "earth-cli-test-*")
	if err != nil {
		return "", nil, err
	}

	binary := filepath.Join(dir, "earth")

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	//nolint:gosec // This test builds the repository's own CLI binary.
	cmd := exec.CommandContext(ctx, "go", "build", "-o", binary, "./cmd/earthly")
	cmd.Dir = repoRoot()

	out, err := cmd.CombinedOutput()
	if err != nil {
		_ = os.RemoveAll(dir)
		return "", nil, fmt.Errorf("%w\n%s", err, out)
	}

	return binary, func() { _ = os.RemoveAll(dir) }, nil
}

func runEarth(t *testing.T, dir string, args ...string) (string, error) {
	t.Helper()

	earthCmdMu.Lock()
	defer earthCmdMu.Unlock()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	//nolint:gosec // The test controls both the binary path and arguments.
	cmd := exec.CommandContext(ctx, testBinary, args...)
	cmd.Dir = dir

	cmd.Env = append(os.Environ(),
		"EARTHLY_DISABLE_AUTO_UPDATE=true",
		"EARTHLY_DISABLE_FRONTEND_DETECTION=true",
	)

	out, err := cmd.CombinedOutput()

	return string(out), err
}

func copyFixtureDir(t *testing.T, fixture string) string {
	t.Helper()

	src := filepath.Join(repoRoot(), "tests", "cli", "testdata", fixture)
	dst := t.TempDir()

	require.NoError(t, os.CopyFS(dst, os.DirFS(src)))

	return dst
}

func replaceVersionLine(t *testing.T, path, versionLine string) {
	t.Helper()

	//nolint:gosec // Test fixture paths are generated by the test helper.
	data, err := os.ReadFile(path)
	require.NoError(t, err)

	lines := bytes.SplitN(data, []byte("\n"), 2)
	require.Len(t, lines, 2)
	lines[0] = []byte(versionLine)

	//nolint:gosec // This writes a temporary test fixture.
	require.NoError(t, os.WriteFile(path, bytes.Join(lines, []byte("\n")), 0o600))
}

func repoRoot() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("failed to locate test source")
	}

	dir := filepath.Dir(file)
	for {
		_, err := os.Stat(filepath.Join(dir, "go.mod"))
		if err == nil {
			return dir
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			panic("failed to locate repository root from " + file)
		}

		dir = parent
	}
}
