VERSION 0.8
FROM ruby:3.4.8
WORKDIR /ruby-example

deps:
    COPY Gemfile Gemfile.lock ./
    RUN  bundle install
    SAVE ARTIFACT Gemfile.lock AS LOCAL ./Gemfile.lock

build:
    FROM +deps
    COPY src src
    SAVE ARTIFACT src /src

docker:
    FROM +deps
    COPY +build/src src
    ENTRYPOINT ["ruby", "./src/hello.rb"]
    SAVE IMAGE --push earthbuild/examples:ruby

# upgrade-deps Update dependencies to latest compatible versions and persist lockfile
upgrade-deps:
    FROM +deps
    RUN bundle update

    SAVE ARTIFACT Gemfile.lock AS LOCAL Gemfile.lock
