VERSION 0.8
my-image:
    FROM alpine
    SAVE IMAGE my/image:test

MY_COMMAND_WITH_DOCKER:
    FUNCTION
    ARG MY_ARG="default"
    WITH DOCKER --load +my-image
        RUN echo "got $MY_ARG"
    END

test:
    FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r3
    DO +MY_COMMAND_WITH_DOCKER --MY_ARG="myvalue"
    DO +MY_COMMAND_WITH_DOCKER
