version: "2"
run:
  timeout: 10m
  tests: true
  # build-tags:
  #   - windows
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godox
    - gomoddirectives
    - goprintffuncname
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mirror
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - prealloc
    - predeclared
    - protogetter
    - recvcheck
    - revive
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - unconvert
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
formatters:
  enable:
    - gofumpt
