version: "2"
run:
  timeout: 10m
  tests: true
  # build-tags:
  #   - windows
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gomoddirectives
    - inamedparam
    - interfacebloat
    - ireturn
    - maintidx
    - mirror
    - mnd
    - musttag
    - nilnesserr
    - nilnil
    - nlreturn
    - nonamedreturns
    - recvcheck
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl # deprecated
  exclusions:
    generated: lax
  settings:
    govet:
      enable-all: true
formatters:
  enable:
    - gofumpt
