[tools]
go = "1.25.5"
prek = "0.4.3"
# renovate: datasource=github-releases packageName=koalaman/shellcheck
shellcheck = "v0.11.0"
# renovate: datasource=github-releases packageName=golangci/golangci-lint
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "v1.64.5"
# renovate: datasource=github-releases packageName=mvdan/gofumpt
"go:mvdan.cc/gofumpt" = "v0.10.0"
