VERSION 0.8
FROM ruby:3.4.8
WORKDIR /ruby-on-rails-example
# renovate: datasource=rubygems packageName=bundler
ENV BUNDLER_VERSION=2.5.9

deps:
    RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
      apt-get install -y nodejs
    RUN gem install bundler:$BUNDLER_VERSION
    COPY Gemfile ./
    COPY --if-exists Gemfile.lock* ./
    RUN bundle config build.nokogiri --use-system-libraries
    RUN bundle check || bundle install
    SAVE ARTIFACT Gemfile.lock AS LOCAL ./Gemfile.lock

build:
    FROM +deps
    COPY . .
    SAVE ARTIFACT . /.

docker:
    FROM +build
    EXPOSE 3000
    CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    SAVE IMAGE --push earthbuild/examples:ruby-on-rails

migrate:
    FROM +build
    RUN --push bundle exec rails db:migrate

test:
    FROM +build
    RUN bundle exec rails test

console:
    FROM +build
    RUN bundle exec rails console

# upgrade-deps Update dependencies to latest compatible versions and persist lockfile
upgrade-deps:
    FROM +deps
    RUN bundle update

    # Save the updated lockfile back to the local workspace
    SAVE ARTIFACT Gemfile.lock AS LOCAL Gemfile.lock
