VERSION 0.8

FROM amazoncorretto:25-alpine3.22

RUN apk add --no-cache ca-certificates curl openssl go && \
    update-ca-certificates

# Install antlr.
WORKDIR /usr/local/lib
# renovate: datasource=github-releases packageName=antlr/antlr4
ARG --global ANTLR_VERSION=4.13.1
RUN echo curl -O https://www.antlr.org/download/antlr-${ANTLR_VERSION}-complete.jar
RUN curl -O https://www.antlr.org/download/antlr-${ANTLR_VERSION}-complete.jar
WORKDIR /earthly

parser:
    COPY ./*.g4 ./ast/parser/
    COPY ./export.go ./ast/parser/
    RUN java \
        -Xmx500M \
        -cp "/usr/local/lib/antlr-${ANTLR_VERSION}-complete.jar:$CLASSPATH" \
        org.antlr.v4.Tool \
        -Dlanguage=Go \
        -lib ast/parser/EarthLexer.g4 \
        -lib ast/parser/EarthParser.g4 \
        ast/parser/EarthLexer.g4 \
        ast/parser/EarthParser.g4
    # Fix for overflow of int on 32bit architectures (eg arm/v7).
    # https://github.com/antlr/antlr4/issues/2433#issuecomment-666056924
    RUN sed -i.bak 's/(1<</(int64(1)<</g' ./ast/parser/*.go
    RUN diff ./ast/parser/earth_parser.go.bak ./ast/parser/earth_parser.go || true
    RUN gofmt -w ./ast/parser/*.go
    SAVE ARTIFACT ./ast/parser/*.go / AS LOCAL ./

test-not-committed:
    COPY ./*.go ./locally/
    COPY +parser/* ./generated/
    RUN diff -qr ./locally ./generated

# To visualize use VSCode extension: https://github.com/mike-lischke/vscode-antlr4
