// Code generated by git.sr.ht/~nelsam/hel. DO NOT EDIT.
//
// This file contains mocks generated by hel. Do not edit this code by
// hand unless you *really* know what you're doing. Expect any changes
// made manually to be overwritten the next time hel regenerates this
// file.

package authprovider_test

import (
	"context"
	"git.sr.ht/~nelsam/hel/pkg/pers"
	"git.sr.ht/~nelsam/hel/vegr"
	"github.com/moby/buildkit/session/auth"
	"io"
	"time"
)

var (
	_ = vegr.EnforceVersion(7 - vegr.MinVersion)
	_ = vegr.EnforceVersion(vegr.MaxVersion - 7)
)

type mockChild_Credentials_In struct {
	Arg0 context.Context
	Arg1 *auth.CredentialsRequest
}

func (mockChild_Credentials_In) Variadic() bool {
	return false
}

type mockChild_Credentials_Out struct {
	Panic_ any
	Ret0   *auth.CredentialsResponse
	Ret1   error
}
type mockChild_Credentials struct {
	vegr.Method[mockChild_Credentials_In, mockChild_Credentials_Out]
}
type mockChild_FetchToken_In struct {
	Arg0 context.Context
	Arg1 *auth.FetchTokenRequest
}

func (mockChild_FetchToken_In) Variadic() bool {
	return false
}

type mockChild_FetchToken_Out struct {
	Panic_ any
	Ret0   *auth.FetchTokenResponse
	Ret1   error
}
type mockChild_FetchToken struct {
	vegr.Method[mockChild_FetchToken_In, mockChild_FetchToken_Out]
}
type mockChild_GetTokenAuthority_In struct {
	Arg0 context.Context
	Arg1 *auth.GetTokenAuthorityRequest
}

func (mockChild_GetTokenAuthority_In) Variadic() bool {
	return false
}

type mockChild_GetTokenAuthority_Out struct {
	Panic_ any
	Ret0   *auth.GetTokenAuthorityResponse
	Ret1   error
}
type mockChild_GetTokenAuthority struct {
	vegr.Method[mockChild_GetTokenAuthority_In, mockChild_GetTokenAuthority_Out]
}
type mockChild_VerifyTokenAuthority_In struct {
	Arg0 context.Context
	Arg1 *auth.VerifyTokenAuthorityRequest
}

func (mockChild_VerifyTokenAuthority_In) Variadic() bool {
	return false
}

type mockChild_VerifyTokenAuthority_Out struct {
	Panic_ any
	Ret0   *auth.VerifyTokenAuthorityResponse
	Ret1   error
}
type mockChild_VerifyTokenAuthority struct {
	vegr.Method[mockChild_VerifyTokenAuthority_In, mockChild_VerifyTokenAuthority_Out]
}
type mockChild struct {
	prefs  vegr.Prefs
	method struct {
		Credentials          mockChild_Credentials
		FetchToken           mockChild_FetchToken
		GetTokenAuthority    mockChild_GetTokenAuthority
		VerifyTokenAuthority mockChild_VerifyTokenAuthority
	}
}

func newMockChild(cst pers.Constructor) *mockChild {
	m := &mockChild{prefs: vegr.MakePrefs(cst)}
	m.method.Credentials.Method = vegr.NewMethod[mockChild_Credentials_In, mockChild_Credentials_Out]("mockChild", "Credentials", 100, vegr.WithPrefs(m.prefs))
	m.method.FetchToken.Method = vegr.NewMethod[mockChild_FetchToken_In, mockChild_FetchToken_Out]("mockChild", "FetchToken", 100, vegr.WithPrefs(m.prefs))
	m.method.GetTokenAuthority.Method = vegr.NewMethod[mockChild_GetTokenAuthority_In, mockChild_GetTokenAuthority_Out]("mockChild", "GetTokenAuthority", 100, vegr.WithPrefs(m.prefs))
	m.method.VerifyTokenAuthority.Method = vegr.NewMethod[mockChild_VerifyTokenAuthority_In, mockChild_VerifyTokenAuthority_Out]("mockChild", "VerifyTokenAuthority", 100, vegr.WithPrefs(m.prefs))
	return m
}
func (m *mockChild) Credentials(arg0 context.Context, arg1 *auth.CredentialsRequest) (ret0 *auth.CredentialsResponse, ret1 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Credentials, mockChild_Credentials_In{Arg0: arg0, Arg1: arg1}, &ret0, &ret1)
	return ret0, ret1
}
func (m *mockChild) FetchToken(arg0 context.Context, arg1 *auth.FetchTokenRequest) (ret0 *auth.FetchTokenResponse, ret1 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.FetchToken, mockChild_FetchToken_In{Arg0: arg0, Arg1: arg1}, &ret0, &ret1)
	return ret0, ret1
}
func (m *mockChild) GetTokenAuthority(arg0 context.Context, arg1 *auth.GetTokenAuthorityRequest) (ret0 *auth.GetTokenAuthorityResponse, ret1 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.GetTokenAuthority, mockChild_GetTokenAuthority_In{Arg0: arg0, Arg1: arg1}, &ret0, &ret1)
	return ret0, ret1
}
func (m *mockChild) VerifyTokenAuthority(arg0 context.Context, arg1 *auth.VerifyTokenAuthorityRequest) (ret0 *auth.VerifyTokenAuthorityResponse, ret1 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.VerifyTokenAuthority, mockChild_VerifyTokenAuthority_In{Arg0: arg0, Arg1: arg1}, &ret0, &ret1)
	return ret0, ret1
}

type mockContext_Deadline_In struct {
}

func (mockContext_Deadline_In) Variadic() bool {
	return false
}

type mockContext_Deadline_Out struct {
	Panic_   any
	Deadline time.Time
	Ok       bool
}
type mockContext_Deadline struct {
	vegr.Method[mockContext_Deadline_In, mockContext_Deadline_Out]
}
type mockContext_Done_In struct {
}

func (mockContext_Done_In) Variadic() bool {
	return false
}

type mockContext_Done_Out struct {
	Panic_ any
	Ret0   <-chan struct{}
}
type mockContext_Done struct {
	vegr.Method[mockContext_Done_In, mockContext_Done_Out]
}
type mockContext_Err_In struct {
}

func (mockContext_Err_In) Variadic() bool {
	return false
}

type mockContext_Err_Out struct {
	Panic_ any
	Ret0   error
}
type mockContext_Err struct {
	vegr.Method[mockContext_Err_In, mockContext_Err_Out]
}
type mockContext_Value_In struct {
	Key any
}

func (mockContext_Value_In) Variadic() bool {
	return false
}

type mockContext_Value_Out struct {
	Panic_ any
	Ret0   any
}
type mockContext_Value struct {
	vegr.Method[mockContext_Value_In, mockContext_Value_Out]
}
type mockContext struct {
	prefs  vegr.Prefs
	method struct {
		Deadline mockContext_Deadline
		Done     mockContext_Done
		Err      mockContext_Err
		Value    mockContext_Value
	}
}

func newMockContext(cst pers.Constructor) *mockContext {
	m := &mockContext{prefs: vegr.MakePrefs(cst)}
	m.method.Deadline.Method = vegr.NewMethod[mockContext_Deadline_In, mockContext_Deadline_Out]("mockContext", "Deadline", 100, vegr.WithPrefs(m.prefs))
	m.method.Done.Method = vegr.NewMethod[mockContext_Done_In, mockContext_Done_Out]("mockContext", "Done", 100, vegr.WithPrefs(m.prefs))
	m.method.Err.Method = vegr.NewMethod[mockContext_Err_In, mockContext_Err_Out]("mockContext", "Err", 100, vegr.WithPrefs(m.prefs))
	m.method.Value.Method = vegr.NewMethod[mockContext_Value_In, mockContext_Value_Out]("mockContext", "Value", 100, vegr.WithPrefs(m.prefs))
	return m
}
func (m *mockContext) Deadline() (deadline time.Time, ok bool) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Deadline, mockContext_Deadline_In{}, &deadline, &ok)
	return deadline, ok
}
func (m *mockContext) Done() (ret0 <-chan struct{}) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Done, mockContext_Done_In{}, &ret0)
	return ret0
}
func (m *mockContext) Err() (ret0 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Err, mockContext_Err_In{}, &ret0)
	return ret0
}
func (m *mockContext) Value(key any) (ret0 any) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Value, mockContext_Value_In{Key: key}, &ret0)
	return ret0
}

type mockProjectAdder_AddProject_In struct {
	Org, Project string
}

func (mockProjectAdder_AddProject_In) Variadic() bool {
	return false
}

type mockProjectAdder_AddProject_Out struct {
	Panic_ any
}
type mockProjectAdder_AddProject struct {
	vegr.Method[mockProjectAdder_AddProject_In, mockProjectAdder_AddProject_Out]
}
type mockProjectAdder struct {
	prefs  vegr.Prefs
	method struct {
		AddProject mockProjectAdder_AddProject
	}
}

func newMockProjectAdder(cst pers.Constructor) *mockProjectAdder {
	m := &mockProjectAdder{prefs: vegr.MakePrefs(cst)}
	m.method.AddProject.Method = vegr.NewMethod[mockProjectAdder_AddProject_In, mockProjectAdder_AddProject_Out]("mockProjectAdder", "AddProject", 100, vegr.WithPrefs(m.prefs))
	return m
}
func (m *mockProjectAdder) AddProject(org, project string) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.AddProject, mockProjectAdder_AddProject_In{Org: org, Project: project})
}

type mockOS_Open_In struct {
	Arg0 string
}

func (mockOS_Open_In) Variadic() bool {
	return false
}

type mockOS_Open_Out struct {
	Panic_ any
	Ret0   io.ReadCloser
	Ret1   error
}
type mockOS_Open struct {
	vegr.Method[mockOS_Open_In, mockOS_Open_Out]
}
type mockOS_Getenv_In struct {
	Arg0 string
}

func (mockOS_Getenv_In) Variadic() bool {
	return false
}

type mockOS_Getenv_Out struct {
	Panic_ any
	Ret0   string
}
type mockOS_Getenv struct {
	vegr.Method[mockOS_Getenv_In, mockOS_Getenv_Out]
}
type mockOS struct {
	prefs  vegr.Prefs
	method struct {
		Open   mockOS_Open
		Getenv mockOS_Getenv
	}
}

func newMockOS(cst pers.Constructor) *mockOS {
	m := &mockOS{prefs: vegr.MakePrefs(cst)}
	m.method.Open.Method = vegr.NewMethod[mockOS_Open_In, mockOS_Open_Out]("mockOS", "Open", 100, vegr.WithPrefs(m.prefs))
	m.method.Getenv.Method = vegr.NewMethod[mockOS_Getenv_In, mockOS_Getenv_Out]("mockOS", "Getenv", 100, vegr.WithPrefs(m.prefs))
	return m
}
func (m *mockOS) Open(arg0 string) (ret0 io.ReadCloser, ret1 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Open, mockOS_Open_In{Arg0: arg0}, &ret0, &ret1)
	return ret0, ret1
}
func (m *mockOS) Getenv(arg0 string) (ret0 string) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Getenv, mockOS_Getenv_In{Arg0: arg0}, &ret0)
	return ret0
}

type mockReadCloser_Read_In struct {
	P []byte
}

func (mockReadCloser_Read_In) Variadic() bool {
	return false
}

type mockReadCloser_Read_Out struct {
	Panic_ any
	N      int
	Err    error
}
type mockReadCloser_Read struct {
	vegr.Method[mockReadCloser_Read_In, mockReadCloser_Read_Out]
}
type mockReadCloser_Close_In struct {
}

func (mockReadCloser_Close_In) Variadic() bool {
	return false
}

type mockReadCloser_Close_Out struct {
	Panic_ any
	Ret0   error
}
type mockReadCloser_Close struct {
	vegr.Method[mockReadCloser_Close_In, mockReadCloser_Close_Out]
}
type mockReadCloser struct {
	prefs  vegr.Prefs
	method struct {
		Read  mockReadCloser_Read
		Close mockReadCloser_Close
	}
}

func newMockReadCloser(cst pers.Constructor) *mockReadCloser {
	m := &mockReadCloser{prefs: vegr.MakePrefs(cst)}
	m.method.Read.Method = vegr.NewMethod[mockReadCloser_Read_In, mockReadCloser_Read_Out]("mockReadCloser", "Read", 100, vegr.WithPrefs(m.prefs))
	m.method.Close.Method = vegr.NewMethod[mockReadCloser_Close_In, mockReadCloser_Close_Out]("mockReadCloser", "Close", 100, vegr.WithPrefs(m.prefs))
	return m
}
func (m *mockReadCloser) Read(p []byte) (n int, err error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Read, mockReadCloser_Read_In{P: p}, &n, &err)
	return n, err
}
func (m *mockReadCloser) Close() (ret0 error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Close, mockReadCloser_Close_In{}, &ret0)
	return ret0
}

type mockWriter_Write_In struct {
	P []byte
}

func (mockWriter_Write_In) Variadic() bool {
	return false
}

type mockWriter_Write_Out struct {
	Panic_ any
	N      int
	Err    error
}
type mockWriter_Write struct {
	vegr.Method[mockWriter_Write_In, mockWriter_Write_Out]
}
type mockWriter struct {
	prefs  vegr.Prefs
	method struct {
		Write mockWriter_Write
	}
}

func newMockWriter(cst pers.Constructor) *mockWriter {
	m := &mockWriter{prefs: vegr.MakePrefs(cst)}
	m.method.Write.Method = vegr.NewMethod[mockWriter_Write_In, mockWriter_Write_Out]("mockWriter", "Write", 100, vegr.WithPrefs(m.prefs))
	return m
}
func (m *mockWriter) Write(p []byte) (n int, err error) {
	m.prefs.T().Helper()
	vegr.Perform(m.prefs.T(), m.method.Write, mockWriter_Write_In{P: p}, &n, &err)
	return n, err
}
