
steps:
  - label: Test
    commands:
      - ./.buildkite/tests.sh
    env:
      EARTHBUILD_INSTALL_ID: "earthbuild-buildkite-macos"
      EARTHBUILD_OS: "darwin"
    agents:
      os: macOS
      arch: amd64
    timeout_in_minutes: 55
