VERSION 0.8
FROM golang:1.27-alpine3.24
WORKDIR /proto-example

proto:
  RUN apk add --no-cache protobuf-dev protobuf
  RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
  COPY api.proto ./
  RUN mkdir pb && protoc --go_out=./pb --go_opt=paths=source_relative api.proto
  SAVE ARTIFACT pb /pb AS LOCAL pb

build:
  COPY go.mod go.sum .
  RUN go mod download
  COPY +proto/pb pb
  COPY main.go ./
  RUN go build -o build/proto-example main.go
  SAVE ARTIFACT build/proto-example

docker:
  COPY +build/proto-example ./
  ENTRYPOINT ["/proto-example/proto-example"]
  SAVE IMAGE proto-example:latest
