package layer

import (
	"bytes"
	"os"
	"testing"

	"github.com/EarthBuild/earthbuild/engine/ir"
)

// Our encoding of a REAPI Directory is protoc's, byte for byte.
//
// **The only check worth making.** Proto3 defines no canonical form, so an
// encoder verified against itself proves nothing: the whole point is that a
// Bazel or Buck2 worker, serialising the same tree with a different library,
// arrives at the same bytes and therefore the same digest. protoc is the
// reference implementation the ecosystem's agreement actually rests on, so the
// vector is generated by it - see testdata/reapi/golden.textproto and the
// transcribed messages beside it.
//
// Regenerate with:
//
//	protoc --proto_path=engine/layer/testdata/reapi \
//	  --encode=build.bazel.remote.execution.v2.Directory \
//	  engine/layer/testdata/reapi/reapi_min.proto \
//	  < engine/layer/testdata/reapi/golden.textproto \
//	  > engine/layer/testdata/reapi/golden.bin
func TestOurDirectoryEncodingIsProtocs(t *testing.T) {
	t.Parallel()

	want, err := os.ReadFile("testdata/reapi/golden.bin")
	if err != nil {
		t.Fatal(err)
	}

	got := encodeDirectory(&scratch{},
		[]reapiFile{
			{
				name: "a.txt",
				hash: hexID("0000000000000000000000000000000000000000000000000000000000000001"),
				size: 3,
			},
			{
				name:       "run.sh",
				hash:       hexID("0000000000000000000000000000000000000000000000000000000000000002"),
				size:       11,
				executable: true,
				props: []reapiProperty{
					{name: "earthbuild.gid", value: "20"},
					{name: "earthbuild.uid", value: "501"},
				},
			},
		},
		[]reapiDir{{
			name: "sub",
			hash: hexID("0000000000000000000000000000000000000000000000000000000000000003"),
			size: 42,
		}},
		[]reapiSymlink{
			{name: "link", target: "a.txt"},
			{
				name:   "owned",
				target: "sub/deep.txt",
				props:  []reapiProperty{{name: "earthbuild.uid", value: "0"}},
			},
		},
		nil,
	)

	if !bytes.Equal(got, want) {
		t.Errorf("our Directory is %d bytes and protoc's is %d"+
			"\n  ours:   %x"+
			"\n  protoc: %x"+
			"\n\n  a worker serialising this tree with a different library would"+
			"\n  compute a different digest, so nothing we name would be found",
			len(got), len(want), got, want)
	}
}

// hexID is a digest written the way a fixture reads best.
func hexID(s string) ir.NodeID {
	var id ir.NodeID

	for i := 0; i < len(s) && i/2 < len(id); i += 2 {
		var v byte

		for _, c := range []byte{s[i], s[i+1]} {
			v <<= 4

			switch {
			case c >= '0' && c <= '9':
				v |= c - '0'
			case c >= 'a' && c <= 'f':
				v |= c - 'a' + 10
			}
		}

		id[i/2] = v
	}

	return id
}
