VERSION 0.8

deps:
    FROM alpine:3.23

    # renovate: datasource=custom.zig packageName=ziglang/zig
    ARG ZIG_VERSION=0.16.0

    ARG TARGETARCH
    IF [ "$TARGETARCH" = "amd64" ]
        ARG ZIG_ARCH="x86_64"
    ELSE IF [ "$TARGETARCH" = "arm64" ]
        ARG ZIG_ARCH="aarch64"
    END
    RUN echo "Installing Zig $ZIG_VERSION for $ZIG_ARCH"
    RUN \
        if echo "$ZIG_VERSION" | grep -q -- "-dev"; then \
            export URL="https://ziglang.org/builds/zig-$ZIG_ARCH-linux-$ZIG_VERSION.tar.xz"; \
        else \
            export URL="https://ziglang.org/download/$ZIG_VERSION/zig-$ZIG_ARCH-linux-$ZIG_VERSION.tar.xz"; \
        fi && \
        wget --tries=5 --timeout=300 --continue -O zig.tar.xz "$URL" && \
        mkdir zig && \
        tar -xvf zig.tar.xz --strip-components 1 -C zig && \
        ln -sf /zig/zig /usr/bin/zig

src:
    FROM +deps
    WORKDIR app
    COPY build.zig .
    COPY src ./src

build:
    FROM +src
    RUN zig build
    SAVE ARTIFACT zig-out/bin/fizzbuzz AS LOCAL fizzbuzz

test:
    FROM +src
    RUN zig test src/main.zig

docker:
    FROM alpine:3.23
    WORKDIR /app
    COPY +build/fizzbuzz .

    ENTRYPOINT ["/app/fizzbuzz"]
    CMD ["10"]
    SAVE IMAGE --push earthbuild/examples:zig
