VERSION 0.8

ARG --global KIND_VERSION=0.30.0

all:
    BUILD +alpine-kind
    BUILD +ubuntu-kind

alpine-kind:
    ARG DIND_IMAGE=earthbuild/dind:alpine-3.22-docker-28.3.3-r1
    FROM $DIND_IMAGE
    RUN wget -O ./kind https://kind.sigs.k8s.io/dl/v$KIND_VERSION/kind-linux-amd64 && chmod +x kind
    WITH DOCKER
        RUN \
            ./kind create cluster --verbosity 99999 --retain --wait 1m; \
            ./kind export logs ./logs; \
            cat ./logs/*.txt; \
            cat ./logs/kind-control-plane/*;
    END

ubuntu-kind:
    ARG DIND_IMAGE=earthbuild/dind:ubuntu-24.04-docker-28.4.0-1
    FROM $DIND_IMAGE
    RUN curl -Lo ./kind https://kind.sigs.k8s.io/dl/v$KIND_VERSION/kind-linux-amd64 && chmod +x kind
    WITH DOCKER
        RUN ./kind create cluster --verbosity 99999 --retain --wait=1m
    END
