VERSION 0.8

FROM alpine:3.24.0

test:
  RUN echo "hello world 3"
  ARG FILE_NAME_PREFIX="helloworld"
  LET file_name="${FILE_NAME_PREFIX}3"
  RUN echo "hello world 3" > $file_name
  SAVE ARTIFACT $file_name

testdir:
    WORKDIR /somedir3
    RUN echo "hello world in dir" > somefile3
    SAVE ARTIFACT /somedir3
