VERSION 0.8
FROM --pass-args ..+base

IMPORT .. AS tests

WORKDIR /test

test:
    COPY expected-*.yml .

    # test earthly runs when no default config is present
    RUN ! test -f /root/.earthly/config.yml
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile="hello.earth" --target="+hello" --output_contains="greetings"

    # test earthly runs with cache size and percentage settings
    RUN earthly config global.cache_size_pct 50
    RUN earthly config global.cache_size_mb 100
    RUN yq '.global.cache_size_pct == 50 and .global.cache_size_mb == 100' /root/.earthly/config.yml | grep true
    DO --pass-args +RUN_EARTHLY_ARGS --earthfile="hello.earth" --target="+hello" --output_contains="greetings"

    RUN touch /tmp/config.yml
    RUN chmod 400 /tmp/config.yml

    # test permission-related errors
    RUN addgroup -S testgroup
    RUN adduser -S -G testgroup testuser

    # required to allow testuser to call +RUN_EARTHLY_ARGS
    RUN chmod 0777 /tmp/earthbuild-script

    # required to allow testuser to call +RUN_EARTHLY_ARGS

    USER testuser
    WORKDIR /home/testuser

    # test correct user location is used by default
    RUN earthly config global.cache_size_mb 10
    RUN test "$(cat /home/testuser/.earthly/config.yml)" = "$(cat /test/expected-1.yml)"

    # test correct user location is used when set elsewhere
    RUN touch ~/.earthly/other-config.yml
    RUN EARTHLY_CONFIG=~/.earthly/other-config.yml earthly config global.cache_size_mb 10
    RUN test "$(cat /home/testuser/.earthly/other-config.yml)" = "$(cat /test/expected-1.yml)"

    # test correct user location is used when set elsewhere with different installation dir
    RUN mkdir ~/.earthly-not-test && touch ~/.earthly-not-test/other-config.yml
    RUN EARTHLY_INSTALLATION_NAME=earthly-test EARTHLY_CONFIG=~/.earthly-not-test/other-config.yml earthly config global.cache_size_mb 10
    RUN test "$(cat /home/testuser/.earthly-not-test/other-config.yml)" = "$(cat /test/expected-1.yml)"

    # test correct user location is used when set with different installation dir
    RUN EARTHLY_INSTALLATION_NAME=earthly-test2 earthly config global.cache_size_mb 10
    RUN test "$(cat /home/testuser/.earthly-test2/config.yml)" = "$(cat /test/expected-1.yml)"

    # check permission error is correctly returned
    COPY hello.earth Earthfile
    RUN ! earthly --config=/tmp/config.yml --verbose +hello > output.txt 2>&1
    RUN cat output.txt | grep 'Error: read config: failed to read from /tmp/config.yml: open /tmp/config.yml: permission denied'

    # check permission error is correctly returned even when earthly attempts to read from the default location
    # to make this test work, a symbolic link is required (chown root:root /home/testuser/.earthly/config.yml doesnt work)
    RUN rm /home/testuser/.earthly/config.yml
    RUN ln -s /tmp/config.yml /home/testuser/.earthly/config.yml

    RUN ! earthly --verbose +hello > output.txt 2>&1
    RUN cat output.txt | grep 'Error: read config: failed to read from /home/testuser/.earthly/config.yml: open /home/testuser/.earthly/config.yml: permission denied'

    # make it obvious that this test passed, due to the previous grep displaying "Error: ..." when it passes
    RUN echo "config test passed"


RUN_EARTHLY_ARGS:
    FUNCTION
    ARG earthfile
    ARG target="+all"
    ARG extra_args
    ARG exec_cmd
    ARG should_fail=false
    ARG output_contains
    DO --pass-args tests+RUN_EARTHLY \
        --earthfile=$earthfile \
        --target=$target \
        --should_fail=$should_fail \
        --exec_cmd=$exec_cmd \
        --output_contains=$output_contains \
        --extra_args=$extra_args
