VERSION 0.8
FROM node:26.8.2-alpine3.24

WORKDIR /example-multirepo

docker:
    RUN npm install -g http-server
    COPY ../html+html/* ./
    COPY ../js+build/* ./
    EXPOSE 8080
    ENTRYPOINT ["http-server", "."]
    SAVE IMAGE --push earthbuild/examples:monorepo
