VERSION 0.8

load-target:
    ARG foo=1
    FROM alpine
    RUN echo "hi" > /tmp/x
    SAVE IMAGE saved:latest

with-docker-load:
    FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r3
    WITH DOCKER --load saved:latest=+load-target
         RUN echo "loaded"
    END

with-docker-load-no-alias:
    BUILD +load-target
    FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r3
    WITH DOCKER --load +load-target
         RUN echo "loaded"
    END

with-docker-load-args:
    BUILD +load-target
    FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r3
    WITH DOCKER --load foo=(+load-target --foo=2)
         RUN echo "loaded"
    END

with-docker-load-remote:
    BUILD +load-target
    FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r3
    WITH DOCKER --load foo=github.com/earthbuild/earthbuild:6610b73131f94cbe594dba3b90665748f21a9b8d+license
         RUN echo "loaded"
    END
