VERSION 0.8
test:
    FROM alpine:3.18
    WORKDIR test

    SAVE IMAGE earthbuild/sap:empty # should exist

    RUN echo "1" > 1
    ENTRYPOINT ls -la /test
    SAVE IMAGE earthbuild/sap:before-push # should exist

    SAVE IMAGE --push earthbuild/sap:first-push # should exist

    RUN --push echo "2" > 2
    SAVE IMAGE --push earthbuild/sap:after-push # should not exist

only-push:
    FROM alpine:3.18
    WORKDIR test

    RUN echo "1" > 1
    ENTRYPOINT ls -la /test

    SAVE IMAGE --push earthbuild/sap:only-push # should exist
