VERSION 0.8
FROM --pass-args ..+base

test:
    RUN mkdir sub
    COPY root.earth Earthfile
    COPY sub.earth sub/Earthfile
    DO --pass-args +RUN_earthbuild_ARGS --target=+test

RUN_earthbuild_ARGS:
    FUNCTION
    ARG earthfile
    ARG target
    ARG should_fail=false
    DO --pass-args ..+RUN_earthbuild \
        --earthfile=$earthfile \
        --target=$target \
        --should_fail=$should_fail
