VERSION 0.8

build:
  FROM node:26.7.0-alpine3.23
  WORKDIR /app
  COPY package.json package-lock.json .
  RUN npm ci
  COPY --dir src .
  COPY jsconfig.json next.config.mjs .
  RUN npm run build
  SAVE ARTIFACT ./out prod

docker:
  FROM nginx:stable-alpine
  COPY +build/prod /usr/share/nginx/html
  SAVE IMAGE --push earthbuild/examples:react

run:
  FROM earthbuild/dind:alpine-3.24-docker-29.5.3-r0
  WITH DOCKER --load app:test=+docker
    RUN docker run --rm -p 3000:80 app:test
  END
