VERSION 0.8

build:
  FROM node:24.9.0-alpine3.22
  WORKDIR /app
  COPY package.json package-lock.json .
  RUN npm ci
  COPY --dir src .
  COPY jsconfig.json next.config.mjs .
  RUN npm run build
  SAVE ARTIFACT ./out prod

docker:
  FROM nginx:stable-alpine
  COPY +build/prod /usr/share/nginx/html
  SAVE IMAGE --push earthly/examples:react

run:
  FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r1
  WITH DOCKER --load app:test=+docker
    RUN docker run --rm -p 3000:80 app:test
  END
