VERSION 0.8
FROM earthbuild/dind:alpine-3.22-docker-28.3.3-r1
WORKDIR /scala-example
RUN apk add --no-cache openjdk17 bash wget postgresql-client gcompat

sbt:
    #Scala
    # Defaults if not specified

    # renovate: datasource=github-releases packageName=sbt/sbt
    ARG sbt_version=2.0.2
    ARG sbt_home=/usr/local/sbt

    # Download and extract from archive
    RUN mkdir -pv "$sbt_home"
    RUN wget -qO - "https://github.com/sbt/sbt/releases/download/v$sbt_version/sbt-$sbt_version.tgz" >/tmp/sbt.tgz
    RUN tar xzf /tmp/sbt.tgz -C "$sbt_home" --strip-components=1
    RUN ln -sv "$sbt_home"/bin/sbt /usr/bin/

    ENV OSTYPE=linux-gnu

    # This triggers a bunch of useful downloads.
    RUN mkdir -p ~/.config/sbt && echo "--allow-empty" > ~/.config/sbt/sbtopts
    RUN sbt --jvm-client "; sbtVersion; shutdown"

project-files:
    FROM +sbt
    COPY build.sbt ./
    COPY project project
    # Run sbt for caching purposes.
    RUN touch a.scala && sbt --jvm-client "; compile; shutdown" && rm a.scala
    SAVE IMAGE --push earthbuild/examples:integration-project-files

build:
    FROM +project-files
    COPY src src
    RUN sbt --jvm-client "; compile; shutdown"

unit-test:
    FROM +project-files
    COPY src src
    RUN sbt --jvm-client "; test; shutdown"

integration-test:
    FROM +project-files
    COPY src src
    COPY docker-compose.yml ./
    WITH DOCKER --compose docker-compose.yml
        RUN while ! pg_isready --host=localhost --port=5432 --dbname=iso3166 --username=postgres; do sleep 1; done ;\
            sbt --jvm-client "; IntegrationTest/test; shutdown"
    END

docker:
    FROM +project-files
    COPY src src
    RUN \
        sbt --jvm-client "; set assembly / test := sbt.protocol.testing.TestResult.Passed; assembly; shutdown" && \
        mv target/assembly/scala-example-assembly-*.jar app.jar
    ENTRYPOINT ["java","-cp","app.jar","Main"]
    SAVE IMAGE --push earthbuild/examples:integration

smoke-test:
    FROM +project-files
    COPY docker-compose.yml ./
    COPY src/smoketest ./
    WITH DOCKER --compose docker-compose.yml --load=+docker
        RUN while ! pg_isready --host=localhost --port=5432 --dbname=iso3166 --username=postgres; do sleep 1; done ;\
            ./smoketest.sh
    END

all:
  BUILD +build
  BUILD +unit-test
  BUILD +integration-test
  BUILD +smoke-test
