VERSION 0.8
FROM amazoncorretto:25.0.3-alpine3.22
RUN apk add --no-cache gradle openjdk21
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
WORKDIR /java-example

deps:
    COPY build.gradle ./
    RUN gradle build
