name: Docker

on:
  workflow_call:

env:
  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
  OTEL_RESOURCE_ATTRIBUTES: ${{ vars.OTEL_RESOURCE_ATTRIBUTES != '' && format('{0},', vars.OTEL_RESOURCE_ATTRIBUTES) || '' }}${{ github.event.pull_request != null && format('vcs.repository.change.id={0},vcs.repository.change.title={1},', github.event.pull_request.number, github.event.pull_request.title) || '' }}cicd.pipeline.run.id=${{ github.run_number }},cicd.pipeline.run.url.full=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }},cicd.pipeline.name=${{ github.workflow }},vcs.revision.id=${{ github.sha }},vcs.ref.name=${{ github.ref_name }},vcs.repository.name=${{ github.repository }},user.id=${{ github.actor }}
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}

jobs:
  init:
    name: Init
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Initializing Docker test suite"

  tests:
    name: Tests
    needs: init
    strategy:
      fail-fast: false
      matrix:
        target:
          - "+test-misc"
          - "+test-no-qemu-group1"
          - "+test-no-qemu-group2"
          - "+test-no-qemu-group3"
          - "+test-no-qemu-group4"
          - "+test-no-qemu-group5"
          - "+test-no-qemu-group6"
          - "+test-no-qemu-group7"
          - "+test-no-qemu-group8"
          - "+test-no-qemu-group9"
          - "+test-no-qemu-group10"
          - "+test-no-qemu-group11"
          - "+test-no-qemu-group12"
          - "+test-no-qemu-slow"
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: ${{ matrix.target }}
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  tests-qemu:
    name: Tests (QEMU)
    needs: init
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-qemu"
      USE_QEMU: true
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  examples:
    name: Examples
    needs: init
    strategy:
      fail-fast: false
      matrix:
        example:
          - "+examples-1"
          - "+examples-2"
          - "+examples-3"
          - "+examples-4"
          - "+examples-5"
    uses: ./.github/workflows/reusable-example.yml
    with:
      EXAMPLE_NAME: ${{ matrix.example }}
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  test-local:
    name: Test Local
    needs: init
    uses: ./.github/workflows/reusable-test-local.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      BINARY_COMPOSE: "\"docker compose\""
      SUDO: ""
    secrets: inherit

  push-integrations:
    name: Push Integrations
    needs: init
    uses: ./.github/workflows/reusable-push-integrations.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  bootstrap-integrations:
    name: Bootstrap Integrations
    needs: init
    uses: ./.github/workflows/reusable-bootstrap-integrations.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  repo-auth-tests:
    name: Repo Auth Tests
    needs: init
    uses: ./.github/workflows/reusable-repo-auth-tests.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  export-test:
    name: Export Test
    needs: init
    uses: ./.github/workflows/reusable-export-test.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  docker-build-integrations:
    name: Docker Build Integrations
    needs: init
    uses: ./.github/workflows/reusable-docker-build-integrations.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  earthbuild-image-test:
    name: EarthBuild Image Test
    needs: init
    uses: ./.github/workflows/reusable-earthbuild-image-tests.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  misc-test-1:
    name: Misc Test 1
    needs: init
    uses: ./.github/workflows/reusable-misc-tests-1.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  misc-test-2:
    name: Misc Test 2
    needs: init
    uses: ./.github/workflows/reusable-misc-tests-2.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  wait-block-main:
    name: Wait Block Main
    needs: init
    uses: ./.github/workflows/reusable-wait-block-main.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  wait-block-targets:
    name: Wait Block Targets
    needs: init
    strategy:
      fail-fast: false
      matrix:
        target:
          - "+test-misc"
          - "+test-no-qemu-group1"
          - "+test-no-qemu-group2"
          - "+test-no-qemu-group3"
          - "+test-no-qemu-group4"
          - "+test-no-qemu-slow"
          - "+test-qemu"
    uses: ./.github/workflows/reusable-wait-block-target.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
      TARGET_NAME: ${{ matrix.target }}
    secrets: inherit

  git-metadata-test:
    name: Git Metadata Test
    needs: init
    uses: ./.github/workflows/reusable-git-metadata-test.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      SUDO: ""
    secrets: inherit

  race-tests:
    name: Race Tests
    needs: init
    strategy:
      fail-fast: false
      matrix:
        target:
          - "+test-misc"
          - "+test-no-qemu-group1"
          - "+test-no-qemu-group2"
          - "+test-no-qemu-group3"
          - "+test-no-qemu-group4"
          - "+test-no-qemu-slow"
    uses: ./.github/workflows/reusable-race-test.yml
    with:
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      TEST_TARGET: ${{ matrix.target }}
      RUNS_ON: "ubuntu-latest"
      USE_QEMU: false
      BINARY: "docker"
      SUDO: ""
    secrets: inherit
