name: Next

on:
  workflow_call:

env:
  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
  OTEL_RESOURCE_ATTRIBUTES: ${{ vars.OTEL_RESOURCE_ATTRIBUTES != '' && format('{0},', vars.OTEL_RESOURCE_ATTRIBUTES) || '' }}${{ github.event.pull_request != null && format('vcs.repository.change.id={0},vcs.repository.change.title={1},', github.event.pull_request.number, github.event.pull_request.title) || '' }}cicd.pipeline.run.id=${{ github.run_number }},cicd.pipeline.run.url.full=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }},cicd.pipeline.name=${{ github.workflow }},vcs.revision.id=${{ github.sha }},vcs.ref.name=${{ github.ref_name }},vcs.repository.name=${{ github.repository }},user.id=${{ github.actor }}
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}

jobs:
  earthly-next-docker-tests-no-qemu-group1:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group1"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group2:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group2"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group3:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group3"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group4:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group4"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group5:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group5"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group6:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group6"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group7:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group7"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group8:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group8"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group9:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group9"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group10:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group10"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group11:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group11"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group12:
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group12"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit
