name: Next

on:
  workflow_call:

env:
  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
  OTEL_RESOURCE_ATTRIBUTES: ${{ vars.OTEL_RESOURCE_ATTRIBUTES != '' && format('{0},', vars.OTEL_RESOURCE_ATTRIBUTES) || '' }}${{ github.event.pull_request != null && format('vcs.repository.change.id={0},vcs.repository.change.title={1},', github.event.pull_request.number, github.event.pull_request.title) || '' }}cicd.pipeline.run.id=${{ github.run_number }},cicd.pipeline.run.url.full=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }},cicd.pipeline.name=${{ github.workflow }},vcs.revision.id=${{ github.sha }},vcs.ref.name=${{ github.ref_name }},vcs.repository.name=${{ github.repository }},user.id=${{ github.actor }}
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}

jobs:
  next-bootstrap-test:
    name: Bootstrap Test
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/stage2-setup
        with:
          BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
          BINARY: "docker"
          USE_NEXT: true
          SUDO: ""
      - name: Verify bootstrap works
        run: ./build/linux/amd64/earthly bootstrap

  earthly-next-docker-tests-no-qemu-group1:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group1"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group2:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group2"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group3:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group3"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group4:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group4"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group5:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group5"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group6:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group6"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group7:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group7"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group8:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group8"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group9:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group9"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group10:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group10"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group11:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group11"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit

  earthly-next-docker-tests-no-qemu-group12:
    needs: next-bootstrap-test
    uses: ./.github/workflows/reusable-test.yml
    with:
      TEST_TARGET: "+test-no-qemu-group12"
      BUILT_EARTH_PATH: "./build/linux/amd64/earthly"
      RUNS_ON: "ubuntu-latest"
      BINARY: "docker"
      USE_NEXT: true
      SUDO: ""
      SKIP_JOB: ${{ needs.next-bootstrap-test.result != 'success' }}
      # EXTRA_ARGS: "--auto-skip"
    secrets: inherit
