name: Podman CI macOs scheduled

on:
  # schedule:
  #   - cron: '0 0 * * *'
  push:

jobs:
  podman-macos-test:
    name: +testing-gha-podman
    runs-on: macos-15 # GitHub Actions the latest tag still uses macos-11, which does not have brew installed by default
    env:
      FORCE_COLOR: 1
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      BUILT_EARTHLY_PATH: build/darwin/amd64/earthly

      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # matches hardware specs of macos-15 self-hosted machine
      # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
      PODMAN_CPUS: 3
      PODMAN_MEMORY_MB: 6144
      PODMAN_DISK_SPACE_GB: 13
    steps:
      - uses: earthbuild/actions-setup@main
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install podman
        run: brew install podman
      - name: Podman Mac Helper
        # the $(ls /opt/homebrew/Cellar/podman) fills in the version number
        run: sudo /opt/homebrew/Cellar/podman/$(ls /opt/homebrew/Cellar/podman)/bin/podman-mac-helper install \
          && echo "DOCKER_HOST=unix:///Users/runner/.local/share/containers/podman/machine/podman-machine-default/podman.sock" >> $GITHUB_ENV
      - name: Init and start podman machine
        run: podman machine init --now --cpus ${{ env.PODMAN_CPUS }} --disk-size ${{ env.PODMAN_DISK_SPACE_GB }} --memory ${{ env.PODMAN_MEMORY_MB }} --rootful=true
      - name: Podman machine ls
        run: podman machine ls
      - name: Podman machine inspect
        run: podman machine inspect podman-machine-default
      - name: Podman info
        run: podman info
      - name: Podman info debug
        run: podman info --debug
      - name: Podman version
        run: podman version
      - name: Virtualization check
        run: sysctl -a | grep machdep.cpu.features
      - name: Configure Earthly to use GCR mirror
        run: |-
          earthly config global.buildkit_additional_config "'[registry.\"docker.io\"]
          mirrors = [\"mirror.gcr.io\"]'"
      - name: Bootstrap Earthly using released earthly
        run: earthly bootstrap
      - name: Build latest earthly using released earthly
        run: earthly -P --use-inline-cache +for-darwin
      - name: Re-bootstrap Earthly using latest earthly build
        run: ${{ env.BUILT_EARTHLY_PATH }} bootstrap
      - name: rebuild earthly using latest earthly build
        run: ${{ env.BUILT_EARTHLY_PATH }} -P --use-inline-cache +for-darwin
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
          echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      # Note - we only run the non-qemu tests here because we have not figured out cross-compilation on Mac using Podman yet
      - name: Execute tests-no-qemu
        run: ${{env.BUILT_EARTHLY_PATH}} --ci -P +test-no-qemu
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      - name: Execute fail test
        run: "! ${{ env.BUILT_EARTHLY_PATH }} --ci ./tests/fail+test-fail"
      - name: Buildkit logs (runs on failure)
        run: podman logs earthly-buildkitd
        if: ${{ failure() }}
