name: Tagged Release

on:
    release:
        types: [published]

env:
  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
  OTEL_RESOURCE_ATTRIBUTES: ${{ vars.OTEL_RESOURCE_ATTRIBUTES != '' && format('{0},', vars.OTEL_RESOURCE_ATTRIBUTES) || '' }}${{ github.event.pull_request != null && format('vcs.repository.change.id={0},vcs.repository.change.title={1},', github.event.pull_request.number, github.event.pull_request.title) || '' }}cicd.pipeline.run.id=${{ github.run_number }},cicd.pipeline.run.url.full=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }},cicd.pipeline.name=${{ github.workflow }},vcs.revision.id=${{ github.sha }},vcs.ref.name=${{ github.ref_name }},vcs.repository.name=${{ github.repository }},user.id=${{ github.actor }}
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}

jobs:
    add-artifacts-to-release:
        runs-on: ubuntu-24.04-arm
        permissions:
            contents: write
            actions: read
        env:
            FORCE_COLOR: 1
            EARTHLY_BUILDKIT_IMAGE: ghcr.io/earthbuild/earthbuild:buildkitd-v0.8.17-fix.1
        steps:
            - uses: earthbuild/actions-setup@main
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.event.release.tag_name }}
                  fetch-depth: 0
            - name: Copy pre-built artifacts to release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_TAG: ${{ github.event.release.tag_name }}
              run: |
                  earthly --ci --push --secret GITHUB_TOKEN=${{ env.GITHUB_TOKEN }} ./release+promote-artifacts-to-gh \
                      --RELEASE_TAG=${{ env.RELEASE_TAG }}
    release-images-to-dockerhub:
        runs-on: ubuntu-24.04-arm
        permissions:
            contents: read
            packages: read
        env:
            FORCE_COLOR: 1
            EARTHLY_BUILDKIT_IMAGE: ghcr.io/earthbuild/earthbuild:buildkitd-v0.8.17-fix.1
        steps:
            - uses: earthbuild/actions-setup@main
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.event.release.tag_name }}
                  fetch-depth: 0
            - name: Copy images from GHCR.io to DockerHub
              env:
                  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
                  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

                  GHCR_USERNAME: ${{ github.actor }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                  RELEASE_TAG: ${{ github.event.release.tag_name }}
              # TODO: set usernames for docker
              run: |
                  earthly --ci --push --secret CONTAINER_REGISTRY_TOKEN=${{ env.GITHUB_TOKEN }} \
                      --secret DEST_CONTAINER_REGISTRY_TOKEN=${{ env.DOCKERHUB_TOKEN }} \
                      ./release+promote-to-dockerhub \
                      --RELEASE_TAG="${{ env.RELEASE_TAG }}" \
                      --CONTAINER_REGISTRY_USER="${{ env.GHCR_USERNAME }}" \
                      --DST_CONTAINER_REGISTRY_USER="${{ env.DOCKERHUB_USERNAME }}"
