name: Repo Auth Tests

on:
  workflow_call:
    inputs:
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      USE_SATELLITE:
        required: false
        type: boolean
        default: false
      SATELLITE_NAME:
        required: false
        type: string

jobs:
  repo-auth-test:
    name: repo auth tests
    if: ${{ !inputs.SKIP_JOB && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ${{inputs.RUNS_ON}}
    services:
      sshd:
        image: rastasheep/ubuntu-sshd:18.04
        ports:
          - 2222:22
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      SSH_PORT: "2222"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
# to regenerate the entries below; run earthbuild ./scripts/tests/auth+generate-github-tasks
# auto-generated-entries start;
      - name: run test-hello-world-no-ssh-agent.sh
        run: env earthbuild=${{inputs.BUILT_EARTHBUILD_PATH}} scripts/tests/auth/test-hello-world-no-ssh-agent.sh
      - name: run test-hello-world-no-ssh-keys.sh
        run: env earthbuild=${{inputs.BUILT_EARTHBUILD_PATH}} scripts/tests/auth/test-hello-world-no-ssh-keys.sh
      - name: run test-hello-world-with-non-authorized-key.sh
        run: env earthbuild=${{inputs.BUILT_EARTHBUILD_PATH}} scripts/tests/auth/test-hello-world-with-non-authorized-key.sh
      - name: run test-self-hosted.sh
        run: env earthbuild=${{inputs.BUILT_EARTHBUILD_PATH}} frontend=${{inputs.BINARY}} scripts/tests/auth/test-self-hosted.sh
# auto-generated-entries end
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthbuild-buildkitd || true
