name: Test earthbuild (-race)

on:
  workflow_call:
    inputs:
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      TEST_TARGET:
        required: true
        type: string
      RUNS_ON:
        required: true
        type: string
      USE_QEMU:
        required: false
        type: boolean
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      EXTRA_ARGS:
        required: false
        type: string
      USE_SATELLITE:
        required: false
        type: boolean
        default: false
      SATELLITE_NAME:
        required: false
        type: string

jobs:
  test-race:
    name: ${{inputs.TEST_TARGET}} (-race)
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Build latest earthbuild/buildkitd image using released earthbuild
        run: ${{ inputs.BUILT_EARTHBUILD_PATH }} --use-inline-cache ./buildkitd+buildkitd --TAG=race-test
      - name: Execute tests
        run: |-
          GORACE="halt_on_error=1" go run -race ./cmd/earthbuild/*.go --buildkit-image ghcr.io/earthbuild/earthbuild:buildkitd-race-test ${{inputs.EXTRA_ARGS}} -P --no-output \
            ${{inputs.TEST_TARGET}}
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: docker logs earthbuild-buildkitd || true
