name: Wait-block-override

on:
  workflow_call:
    inputs:
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      TARGET_NAME:
        required: true
        type: string
      EXTRA_ARGS:
        required: false
        type: string
      USE_SATELLITE:
        required: false
        type: boolean
        default: false
      SATELLITE_NAME:
        required: false
        type: string

jobs:
  test:
    name: ${{inputs.TARGET_NAME}} (--global-wait-end)
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
          DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
          DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Execute ${{inputs.TARGET_NAME}} using wait-block override
        run: |-
          ${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} ${{inputs.EXTRA_ARGS}} --ci -P --global-wait-end \
           ${{inputs.TARGET_NAME}} --GLOBAL_WAIT_END=true
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthbuild-buildkitd || true
