name: docker-build Integrations

on:
  workflow_call:
    inputs:
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      BINARY:
        type: string
        required: false
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      EARTHBUILD_ORG:
        required: false
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false

jobs:
  docker-build-integration:
    if: ${{ !inputs.SKIP_JOB && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_ORG: "${{inputs.EARTHBUILD_ORG}}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
      DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: run docker-build-integration
        run: ${{inputs.SUDO}} env earthbuild=${{inputs.BUILT_EARTHBUILD_PATH}} scripts/tests/docker-build/integration.sh
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} docker logs earthbuild-buildkitd || true
