name: Earthly Image Tests

on:
  workflow_call:
    inputs:
      BUILT_EARTHLY_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      USE_SATELLITE:
        required: false
        type: boolean
        default: false
      SATELLITE_NAME:
        required: false
        type: string


jobs:
  earthly-image-tests:
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BUILT_EARTHLY_PATH: "${{ inputs.BUILT_EARTHLY_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
          echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Build the earthly docker image
        run: ${{inputs.SUDO}} ${{inputs.BUILT_EARTHLY_PATH}} +earthly-docker --TAG=image-test
      - name: "Run the earthly image tests"
        run: FRONTEND=${{inputs.BINARY}} EARTHLY_IMAGE=earthly/earthly:image-test DOCKERHUB_MIRROR_USERNAME="${{ secrets.DOCKERHUB_MIRROR_USERNAME }}" DOCKERHUB_MIRROR_PASSWORD="${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}" DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" DOCKERHUB_PASSWORD="${{ secrets.DOCKERHUB_TOKEN }}" ./scripts/tests/earthly-image.sh
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthly-buildkitd
