name: Test Earthly (-race)

on:
  workflow_call:
    inputs:
      BUILT_EARTHLY_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      TEST_TARGET:
        required: true
        type: string
      RUNS_ON:
        required: true
        type: string
      USE_QEMU:
        required: false
        type: boolean
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      EXTRA_ARGS:
        required: false
        type: string
      USE_SATELLITE:
        required: false
        type: boolean
        default: false
      SATELLITE_NAME:
        required: false
        type: string

jobs:
  test-race:
    name: ${{inputs.TEST_TARGET}} (-race)
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BUILT_EARTHLY_PATH: "${{ inputs.BUILT_EARTHLY_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
          echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Build latest earthly/buildkitd image using released earthly
        run: ${{ inputs.BUILT_EARTHLY_PATH }} --use-inline-cache ./buildkitd+buildkitd --TAG=race-test
      - name: Execute tests
        run: |-
          GORACE="halt_on_error=1" go run -race ./cmd/earthly/*.go --buildkit-image ghcr.io/earthbuild/earthbuild:buildkitd-race-test ${{inputs.EXTRA_ARGS}} -P --no-output \
            ${{inputs.TEST_TARGET}}
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: docker logs earthly-buildkitd || true
