name: Test Earthly

on:
  workflow_call:
    inputs:
      TEST_TARGET:
        required: true
        type: string
      BUILT_EARTHLY_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      USE_QEMU:
        required: false
        type: boolean
      EARTHLY_ORG:
        required: false
        type: string
      EXTRA_ARGS:
        required: false
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      USE_NEXT:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: +testing-gha-${{inputs.RUNS_ON}}-${{inputs.BINARY}}
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHLY_INSTALL_ID: "earthly-githubactions"
      EARTHLY_ORG: "${{inputs.EARTHLY_ORG}}"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # The dind detects the host's IPv6 capability and then requires IPv6 NAT
      # to create networks for kind. So we load it here.
      # Ref: https://github.com/moby/moby/pull/47062
      - name: Load kernel module IPv6 NAT for kind
        if: ${{ inputs.TEST_TARGET == '+test-no-qemu-kind' }}
        run: sudo modprobe ip6table_nat
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BUILT_EARTHLY_PATH: "${{ inputs.BUILT_EARTHLY_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          USE_QEMU: "${{ inputs.USE_QEMU }}"
          USE_NEXT: "${{ inputs.USE_NEXT }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHLY_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHLY_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthly_version_flag_overrides)"
          echo "EARTHLY_VERSION_FLAG_OVERRIDES=$EARTHLY_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Execute ${{ inputs.TEST_TARGET }} (Earthly Only)
        run: |-
          ${{inputs.SUDO}} ${{ inputs.BUILT_EARTHLY_PATH }} ${{inputs.EXTRA_ARGS}} --ci -P ${{inputs.TEST_TARGET}}
      - name: Display buildkit version
        run: |-
          ${{inputs.SUDO}} ${{inputs.BINARY}} ps -a
          ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthly-buildkitd |& grep 'starting earthly-buildkit'
        shell: bash
      - name: Execute fail test
        run: |
          ! ${{inputs.SUDO}} GITHUB_ACTIONS="" ${{ inputs.BUILT_EARTHLY_PATH }} ${{inputs.EXTRA_ARGS}} --ci ./tests/fail+test-fail
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthly-buildkitd || true
