name: Runs examples1

on:
  workflow_call:
    inputs:
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      USE_QEMU:
        required: false
        type: boolean
      EXAMPLE_NAME:
        required: true
        type: string
      EARTHBUILD_ORG:
        required: false
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false


jobs:
  example:
    name: ${{inputs.EXAMPLE_NAME}}-${{inputs.RUNS_ON}}-${{inputs.BINARY}}
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      EARTHBUILD_ORG: "${{inputs.EARTHBUILD_ORG}}"
      DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
      DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          USE_QEMU: "${{ inputs.USE_QEMU }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Link earthbuild dir to earthbuild dev dir
        run: mkdir -p ~/.earthbuild && ln -s ~/.earthbuild ~/.earthbuild-dev
      - name: Build ${{inputs.EXAMPLE_NAME}} (PR build)
        run: ${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} --ci -P ${{inputs.EXAMPLE_NAME}}
        if: github.event_name != 'push'
      - name: Build ${{inputs.EXAMPLE_NAME}} (main build)
        run: ${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} --ci --push -P ${{inputs.EXAMPLE_NAME}}
        if: github.event_name == 'push'
      - name: Build and test multi-platform example
        run: |
          ${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} ./examples/multiplatform+all
          ${{inputs.SUDO}} ${{inputs.BINARY}} run --rm earthbuild/examples:multiplatform_linux_arm64 | grep aarch64
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthbuild-buildkitd || true
