name: Runs test local

on:
  workflow_call:
    inputs:
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      RUN_EARTHBUILD_TEST_ARGS:
        required: false
        type: string
        default: "--use-inline-cache --save-inline-cache --no-output"
      BINARY:
        required: true
        type: string
      BINARY_COMPOSE:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      EARTHBUILD_ORG:
        required: false
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false


jobs:
  test-local:
    name: test-local ${{inputs.BINARY}}
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      EARTHBUILD_ORG: "${{inputs.EARTHBUILD_ORG}}"
      DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
      DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          DOCKERHUB_MIRROR_USERNAME: "${{ secrets.DOCKERHUB_MIRROR_USERNAME }}"
          DOCKERHUB_MIRROR_PASSWORD: "${{ secrets.DOCKERHUB_MIRROR_PASSWORD }}"
          DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
          DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Execute test-local
        run: "${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} ${{inputs.RUN_EARTHBUILD_TEST_ARGS}} ./tests/local+test-local --FRONTEND=${{inputs.BINARY}}"
      - name: Execute test-local --push
        run: "${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} ${{inputs.RUN_EARTHBUILD_TEST_ARGS}} --push ./tests/local+test-local --FRONTEND=${{inputs.BINARY}}"
      - name: Run general local tests (TODO this is re-testing the +test-local target)
        run: "${{inputs.SUDO}} ${{inputs.BUILT_EARTHBUILD_PATH}} ${{inputs.RUN_EARTHBUILD_TEST_ARGS}} ./tests/local+all --FRONTEND=${{inputs.BINARY}} --FRONTEND_COMPOSE=${{inputs.BINARY_COMPOSE}}"
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthbuild-buildkitd || true
