name: Test earthbuild

on:
  workflow_call:
    inputs:
      TEST_TARGET:
        required: true
        type: string
      BUILT_EARTHBUILD_PATH:
        required: true
        type: string
      BINARY:
        required: true
        type: string
      SUDO:
        type: string
        required: false
      RUNS_ON:
        required: true
        type: string
      USE_QEMU:
        required: false
        type: boolean
      EARTHBUILD_ORG:
        required: false
        type: string
      EXTRA_ARGS:
        required: false
        type: string
      SKIP_JOB:
        required: false
        type: boolean
        default: false
      USE_NEXT:
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: +testing-gha-${{inputs.RUNS_ON}}-${{inputs.BINARY}}
    if: ${{!inputs.SKIP_JOB}}
    runs-on: ${{inputs.RUNS_ON}}
    env:
      FORCE_COLOR: 1
      EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
      EARTHBUILD_INSTALL_ID: "earthbuild-githubactions"
      EARTHBUILD_ORG: "${{inputs.EARTHBUILD_ORG}}"
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/stage2-setup
        with:
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          EARTHBUILD_TOKEN: "${{ secrets.EARTHBUILD_TOKEN }}"
          built_earthbuild_path: "${{ inputs.BUILT_EARTHBUILD_PATH }}"
          BINARY: "${{ inputs.BINARY }}"
          USE_QEMU: "${{ inputs.USE_QEMU }}"
          USE_NEXT: "${{ inputs.USE_NEXT }}"
          SUDO: "${{ inputs.SUDO }}"
      - name: Set EARTHBUILD_VERSION_FLAG_OVERRIDES env
        run: |-
          set -euo pipefail
          EARTHBUILD_VERSION_FLAG_OVERRIDES="$(tr -d '\n' < .earthbuild_version_flag_overrides)"
          echo "EARTHBUILD_VERSION_FLAG_OVERRIDES=$EARTHBUILD_VERSION_FLAG_OVERRIDES" >> "$GITHUB_ENV"
      - name: Execute ${{ inputs.TEST_TARGET }} (earthbuild Only)
        run: |-
          ${{inputs.SUDO}} ${{ inputs.BUILT_EARTHBUILD_PATH }} ${{inputs.EXTRA_ARGS}} --ci -P ${{inputs.TEST_TARGET}}
      - name: Display buildkit version
        run: |-
          ${{inputs.SUDO}} ${{inputs.BINARY}} ps -a
          ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthbuild-buildkitd |& grep 'starting earthbuild-buildkit'
        shell: bash
      - name: Execute fail test
        run: |
          ! ${{inputs.SUDO}} GITHUB_ACTIONS="" ${{ inputs.BUILT_EARTHBUILD_PATH }} ${{inputs.EXTRA_ARGS}} --ci ./tests/fail+test-fail
      - name: Buildkit logs (runs on failure)
        if: ${{ failure() }}
        run: ${{inputs.SUDO}} ${{inputs.BINARY}} logs earthbuild-buildkitd || true
