VERSION 0.8
FROM node:24.9.0-alpine3.22

WORKDIR /example-multirepo

docker:
    RUN npm install -g http-server
    COPY github.com/EarthBuild/earthly-example-multirepo-static:main+html/* ./
    COPY github.com/EarthBuild/earthly-example-multirepo-js:main+build/* ./
    EXPOSE 8080
    ENTRYPOINT ["http-server", "."]
    SAVE IMAGE --push earthbuild/examples:multirepo
